version: '3.16'
services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=playground
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SECRET=6724873005:AAHDEyQgSZ9X7YtaivKCUCqzf_D-UyFm6Ac
    volumes:
      - .:/app
    depends_on:
      - db
    command: sh -c "sleep 10 && python main.py"

